// Generated by CoffeeScript 1.7.1
(function() {
  var documentView;

  documentView = angular.module('documentView', ['musicSVG']);

  documentView.directive('documentView', function() {
    return {
      restrict: 'A',
      require: 'ngModel',
      scope: {
        ngModel: '='
      },
      controller: [
        '$scope', function($scope) {
          return $scope.model = {
            notes: [
              {
                pitch: 69,
                duration: {
                  n: 1,
                  d: 4
                }
              }, {
                pitch: 70,
                duration: {
                  n: 1,
                  d: 4
                }
              }, {
                pitch: 71,
                duration: {
                  n: 1,
                  d: 4
                }
              }, {
                pitch: 72,
                duration: {
                  n: 1,
                  d: 4
                }
              }, {
                pitch: 73,
                duration: {
                  n: 1,
                  d: 4
                }
              }
            ]
          };
        }
      ],
      template: '<svg class="staff" width="480" height="60" viewBox="0 -4 64 8"> <line ng-line width="64"/> </svg> <svg ng-measure ng-model="model" class="staff" width="480" height="60" viewBox="0 -4 64 8"/>'
    };
  });


  /*
      '<svg class="staff" width="480" height="60" viewBox="0 -4 64 8">
        <g ng-staff width="64"/>
        <g ng-repeat="height in [-2,-1,0,1,2]"
          ng-positioned-note type="4" position="{{height}}" x="{{2 * (height + 2) + 1}}"/>
      </svg>'
   */

}).call(this);
