// Generated by CoffeeScript 1.7.1
(function() {
  var fs;

  require('nw.gui').Window.get().showDevTools();

  fs = require('fs');

  $(function() {
    return $('#loadFile').on('click', function() {
      return LZADialog.selectFile({}, function(file) {
        var data, dir, filename, path;
        path = file.path;
        filename = file.name;
        dir = path.replace(filename, '');
        data = new FileReader();
        data.readAsText(file);
        return data.onloadend = function() {
          var e, fileContents;
          try {
            fileContents = JSON.parse(data.result);
            alert('Successfully read file!');
            return console.log(fileContents);
          } catch (_error) {
            e = _error;
            return alert('Unreadable file');
          }
        };
      });
    });
  });

}).call(this);

//# sourceMappingURL=init.map
